name: ats-smart-contract

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
  optimize_wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: build the wasm
        run: docker run --rm -v $(CURDIR):/code:Z \
                  --mount type=volume,source=ats-smart-contract_cache,target=/code/target \
                  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
                  cosmwasm/rust-optimizer:0.10.7