name: Tests
#  Tests  workflow runs integration tests with Provenance
#  This workflow is run on pushes to master & every Pull Request,
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  #  This action cleans up previously running instances of a workflow on the same branch. This accomplishes
  #  the task of automatically cancelling CI runs on pushes to the same branch, which is a common feature in
  #  most CI systems but currently not possible with GitHub actions.
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.3.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main'"

  build_init:
    runs-on: ubuntu-latest
    name: Build Init
    steps:
      - id: version
        run: echo "::set-output name=version::${GITHUB_REF##*/}"
    outputs:
      version: ${{ steps.version.outputs.version }}
      go_version: "1.17"

  test_ats_smart_contract:
    runs-on: ubuntu-latest
    needs:
      - build_init
    name: Test ATS Smart Contract
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: ${{ needs.build_init.outputs.go_version }}
      - name: Build ATS smart contract
        run: |
          make all
      - name: Run ATS Test
        uses: provenance-io/provenance-testing-action@v1.0.0
        with:
          provenance_version: "v1.8.0"
          test_script: "./scripts/test_ats.sh"